[2023-03-18T17:28:43.223+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: vehiclepositions.download_file manual__2023-03-18T17:28:39.933392+00:00 [queued]>
[2023-03-18T17:28:43.255+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: vehiclepositions.download_file manual__2023-03-18T17:28:39.933392+00:00 [queued]>
[2023-03-18T17:28:43.256+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-18T17:28:43.256+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-18T17:28:43.256+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-18T17:28:43.292+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): download_file> on 2023-03-18 17:28:39.933392+00:00
[2023-03-18T17:28:43.299+0000] {standard_task_runner.py:55} INFO - Started process 87636 to run task
[2023-03-18T17:28:43.311+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'vehiclepositions', 'download_file', 'manual__2023-03-18T17:28:39.933392+00:00', '--job-id', '699', '--raw', '--subdir', 'DAGS_FOLDER/vehiclepositions.py', '--cfg-path', '/tmp/tmptb2c22wz']
[2023-03-18T17:28:43.314+0000] {standard_task_runner.py:83} INFO - Job 699: Subtask download_file
[2023-03-18T17:28:43.488+0000] {task_command.py:388} INFO - Running <TaskInstance: vehiclepositions.download_file manual__2023-03-18T17:28:39.933392+00:00 [running]> on host diploma-vm.europe-west1-b.c.diploma-380314.internal
[2023-03-18T17:28:43.595+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=vehiclepositions
AIRFLOW_CTX_TASK_ID=download_file
AIRFLOW_CTX_EXECUTION_DATE=2023-03-18T17:28:39.933392+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-18T17:28:39.933392+00:00
[2023-03-18T17:28:43.674+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/melicharovykrecek/diploma/dags/vehiclepositions.py", line 43, in download_file
    response = response['features']
TypeError: 'Response' object is not subscriptable
[2023-03-18T17:28:43.688+0000] {taskinstance.py:1318} INFO - Marking task as FAILED. dag_id=vehiclepositions, task_id=download_file, execution_date=20230318T172839, start_date=20230318T172843, end_date=20230318T172843
[2023-03-18T17:28:43.702+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 699 for task download_file ('Response' object is not subscriptable; 87636)
[2023-03-18T17:28:43.720+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-18T17:28:43.755+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
