[2023-03-18T08:27:00.628+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: parking_spaces.create_table_parking_spaces manual__2023-03-18T08:26:56.735544+00:00 [queued]>
[2023-03-18T08:27:00.643+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: parking_spaces.create_table_parking_spaces manual__2023-03-18T08:26:56.735544+00:00 [queued]>
[2023-03-18T08:27:00.643+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-18T08:27:00.644+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-18T08:27:00.644+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-18T08:27:00.663+0000] {taskinstance.py:1300} INFO - Executing <Task(MySqlOperator): create_table_parking_spaces> on 2023-03-18 08:26:56.735544+00:00
[2023-03-18T08:27:00.670+0000] {standard_task_runner.py:55} INFO - Started process 58783 to run task
[2023-03-18T08:27:00.678+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'parking_spaces', 'create_table_parking_spaces', 'manual__2023-03-18T08:26:56.735544+00:00', '--job-id', '538', '--raw', '--subdir', 'DAGS_FOLDER/parking_spaces.py', '--cfg-path', '/tmp/tmpinn74uol']
[2023-03-18T08:27:00.681+0000] {standard_task_runner.py:83} INFO - Job 538: Subtask create_table_parking_spaces
[2023-03-18T08:27:00.803+0000] {task_command.py:388} INFO - Running <TaskInstance: parking_spaces.create_table_parking_spaces manual__2023-03-18T08:26:56.735544+00:00 [running]> on host diploma-vm.europe-west1-b.c.diploma-380314.internal
[2023-03-18T08:27:00.849+0000] {abstractoperator.py:609} ERROR - Exception rendering Jinja template for task 'create_table_parking_spaces', field 'sql'. Template: '/parking/create_table.sql'
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 602, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 657, in render_template
    template = jinja_env.get_template(value)
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /parking/create_table.sql
[2023-03-18T08:27:00.854+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1374, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1493, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2115, in render_templates
    original_task.render_template_fields(context)
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1179, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 602, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 657, in render_template
    template = jinja_env.get_template(value)
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /parking/create_table.sql
[2023-03-18T08:27:00.874+0000] {taskinstance.py:1318} INFO - Marking task as FAILED. dag_id=parking_spaces, task_id=create_table_parking_spaces, execution_date=20230318T082656, start_date=20230318T082700, end_date=20230318T082700
[2023-03-18T08:27:00.892+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 538 for task create_table_parking_spaces (/parking/create_table.sql; 58783)
[2023-03-18T08:27:00.931+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-18T08:27:00.981+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
