[2023-03-17T19:09:26.240+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: get_file_from_endpoint.insert_values_parking_measurements manual__2023-03-17T19:08:40.367919+00:00 [queued]>
[2023-03-17T19:09:26.253+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: get_file_from_endpoint.insert_values_parking_measurements manual__2023-03-17T19:08:40.367919+00:00 [queued]>
[2023-03-17T19:09:26.253+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-17T19:09:26.253+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-17T19:09:26.253+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-17T19:09:26.268+0000] {taskinstance.py:1300} INFO - Executing <Task(MySqlOperator): insert_values_parking_measurements> on 2023-03-17 19:08:40.367919+00:00
[2023-03-17T19:09:26.273+0000] {standard_task_runner.py:55} INFO - Started process 7929 to run task
[2023-03-17T19:09:26.279+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_file_from_endpoint', 'insert_values_parking_measurements', 'manual__2023-03-17T19:08:40.367919+00:00', '--job-id', '258', '--raw', '--subdir', 'DAGS_FOLDER/api.py', '--cfg-path', '/tmp/tmpy3sj0xaz']
[2023-03-17T19:09:26.282+0000] {standard_task_runner.py:83} INFO - Job 258: Subtask insert_values_parking_measurements
[2023-03-17T19:09:26.376+0000] {task_command.py:388} INFO - Running <TaskInstance: get_file_from_endpoint.insert_values_parking_measurements manual__2023-03-17T19:08:40.367919+00:00 [running]> on host diploma-vm.europe-west1-b.c.diploma-380314.internal
[2023-03-17T19:09:26.458+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=get_file_from_endpoint
AIRFLOW_CTX_TASK_ID=insert_values_parking_measurements
AIRFLOW_CTX_EXECUTION_DATE=2023-03-17T19:08:40.367919+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-17T19:08:40.367919+00:00
[2023-03-17T19:09:26.459+0000] {sql.py:254} INFO - Executing: INSERT INTO pre_parking_measurements VALUES ('0','{"error_message": "Unauthorized. Failed to authenticate user.", "error_status": 401}',' 0 ','2023-03-17 19:09:26.079614','1');
[2023-03-17T19:09:26.486+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/providers/common/sql/operators/sql.py", line 255, in execute
    hook = self.get_db_hook()
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/providers/common/sql/operators/sql.py", line 179, in get_db_hook
    return self._hook
  File "/usr/lib/python3.9/functools.py", line 969, in __get__
    val = self.func(instance)
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/providers/common/sql/operators/sql.py", line 141, in _hook
    conn = BaseHook.get_connection(self.conn_id)
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/models/connection.py", line 435, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `mysql_localhost` isn't defined
[2023-03-17T19:09:26.497+0000] {taskinstance.py:1318} INFO - Marking task as FAILED. dag_id=get_file_from_endpoint, task_id=insert_values_parking_measurements, execution_date=20230317T190840, start_date=20230317T190926, end_date=20230317T190926
[2023-03-17T19:09:26.510+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 258 for task insert_values_parking_measurements (The conn_id `mysql_localhost` isn't defined; 7929)
[2023-03-17T19:09:26.531+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-17T19:09:26.554+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
